In [82]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
countries_csv = "./resources/countries.csv"

# Read countries Data File and store into Pandas Data Frames
countries_data = pd.read_csv(countries_csv)

countries_df = countries_data[['Country Name',
                'Time',
                'Renewable electricity output (GWh) [4.1.2_REN.ELECTRICITY.OUTPUT]',
                'Total electricity output (GWh) [4.1.1_TOTAL.ELECTRICITY.OUTPUT]',
                'Renewable energy consumption (TJ) [3.1_RE.CONSUMPTION]',
                'Total final energy consumption (TFEC) (TJ) [1.1_TOTAL.FINAL.ENERGY.CONSUM]'
               ]]

# countries_df = countries_df.replace('..',-1)

countries_df.dtypes
countries_df['Renewable electricity output (GWh) [4.1.2_REN.ELECTRICITY.OUTPUT]'] = pd.to_numeric(countries_df['Renewable electricity output (GWh) [4.1.2_REN.ELECTRICITY.OUTPUT]'],errors='coerce')
countries_df.head(20)

/Users/choki/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Country Name,Time,Renewable electricity output (GWh) [4.1.2_REN.ELECTRICITY.OUTPUT],Total electricity output (GWh) [4.1.1_TOTAL.ELECTRICITY.OUTPUT],Renewable energy consumption (TJ) [3.1_RE.CONSUMPTION],Total final energy consumption (TFEC) (TJ) [1.1_TOTAL.FINAL.ENERGY.CONSUM]
0,Afghanistan,2006.0,646.0,913,14324.37,38571.43487
1,Afghanistan,2007.0,684.0,950,15270.5,45095.50226
2,Afghanistan,2008.0,541.0,788,15312.85,71744.09407
3,Afghanistan,2009.0,775.0,889,16854.19,94612.81812
4,Afghanistan,2010.0,767.0,892,19578.7,131933.6658
5,Afghanistan,2011.0,829.0,1005,20435.21,177965.1033
6,Afghanistan,2012.0,878.0,1022,22561.36,161457.1986
7,Afghanistan,2013.0,803.9,1022.3,22073.09,135133.4316
8,Afghanistan,2014.0,895.3,1049.3,24448.73,126583.7733
9,Afghanistan,2015.0,889.5,1033.7,25134.53,136426.6353
10,Afghanistan,2016.0,NaN,..,..,..
11,Albania,2006.0,5431.0,5524,22033.78,69484.84456
12,Albania,2007.0,2788.0,2860,22144.92,68985.27558
13,Albania,2008.0,3797.0,3797,25902.98,72127.21777
14,Albania,2009.0,5201.0,5202,28426.24,76380.46229
15,Albania,2010.0,7567.0,7568,29286.06,78905.56324
16,Albania,2011.0,4132.0,4191,29278.34,81413.45644
17,Albania,2012.0,4725.0,4725,29877.97,74604.84041
18,Albania,2013.0,6959.0,6959,33755.15,81753.4246
19,Albania,2014.0,4724.0,4724,33160.59,85709.53192

In [73]:
def test(value):
    return (value).mean()

# Group data by country

df.head(20)

0      646.0
1      684.0
2      541.0
3      775.0
4      767.0
5      829.0
6      878.0
7      803.9
8      895.3
9      889.5
10      -1.0
11    5431.0
12    2788.0
13    3797.0
14    5201.0
15    7567.0
16    4132.0
17    4725.0
18    6959.0
19    4724.0
Name: Renewable electricity output (GWh) [4.1.2_REN.ELECTRICITY.OUTPUT], dtype: float64